#ifndef CONNECTIONPOOL_GLOBAL_H
#define CONNECTIONPOOL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONNECTIONPOOL_LIBRARY)
#  define CONNECTIONPOOLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONNECTIONPOOLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONNECTIONPOOL_GLOBAL_H
